### ISSUE TITLE
Is it necessary to mount the image?

### ISSUE THREAD

**Issue by emiljoensson** [michabbs/lvm2pbs#1]
Can't we just specify the snapshot (e.g /dev/vgname/lvname_snapshot) as source?

**Comment by michabbs** [comment]
1. [raw image mode]
When you already did the snapshot yourself, then you do not need this script at all. Just run "proxmox-backup-client backup [some_options] archive_name.img:/dev/vgname/lvname_snapshot".

2. [filessytem archive mode]
Snapshot must be mounted in order to backup hierarchical structure of folders.
